# Generated by Django 3.2.5 on 2021-07-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FIRSTAPP', '0002_address_contact_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='subjects',
            new_name='subject_id',
        ),
    ]
